---
name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.2.0
      - name: Build Docker images
        uses: docker/bake-action@v7.2.0
        with:
          pull: true
          load: true
          source: .
          files: |
            compose.yaml
            compose.override.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max
      - name: Start services
        run: docker compose up --wait --no-build
      - name: Install dependencies
        run: docker compose exec -T php composer install --no-interaction --prefer-dist
      - name: PHP-CS-Fixer
        run: docker compose exec -T php vendor/bin/php-cs-fixer fix --dry-run --diff
      - name: PHPStan
        run: docker compose exec -T php vendor/bin/phpstan analyse --no-progress --memory-limit=1G
      - name: Create test database
        run: docker compose exec -T php bin/console -e test doctrine:database:create
      - name: Run migrations
        run: docker compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction
      - name: Run PHPUnit
        run: docker compose exec -T php bin/phpunit
      - name: Check HTTP reachability
        run: curl -v --fail-with-body http://localhost
      # Uncomment when the homepage is configured, or change the path to check
      # - name: Check HTTPS reachability
      #   run: curl -v --insecure --fail-with-body https://localhost
      - name: Check Mercure reachability
        run: curl -vI --insecure --fail-with-body https://localhost/.well-known/mercure?topic=test
